apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: hw4
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - jobs
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
      - batch
    resources:
      - deployments
      - jobs
      - pods
